// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2gRMsbG0OE_-jQ0uxuhUUFuqF6PzR9_s',
    appId: '1:1082988640492:web:1be1f677efd5eeb0b84dc9',
    messagingSenderId: '1082988640492',
    projectId: 'kazguu-670b2',
    authDomain: 'kazguu-670b2.firebaseapp.com',
    storageBucket: 'kazguu-670b2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxuRwJTiBJgW8-POpAIvMk85lmcOWWH3U',
    appId: '1:1082988640492:android:0e63b891b76d17ebb84dc9',
    messagingSenderId: '1082988640492',
    projectId: 'kazguu-670b2',
    storageBucket: 'kazguu-670b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-LdJYEVYAf11RvTwwa-GYe_07zFX6j6s',
    appId: '1:1082988640492:ios:20b3d7d42c7116f4b84dc9',
    messagingSenderId: '1082988640492',
    projectId: 'kazguu-670b2',
    storageBucket: 'kazguu-670b2.appspot.com',
    androidClientId: '1082988640492-s2s8mu176le0tlj86sel8v80894lbtp9.apps.googleusercontent.com',
    iosClientId: '1082988640492-2afh2imer6bkl0utk2t3sg9357meolog.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2gRMsbG0OE_-jQ0uxuhUUFuqF6PzR9_s',
    appId: '1:1082988640492:web:32bc59e67e1e461cb84dc9',
    messagingSenderId: '1082988640492',
    projectId: 'kazguu-670b2',
    authDomain: 'kazguu-670b2.firebaseapp.com',
    storageBucket: 'kazguu-670b2.appspot.com',
  );
}
